default_stages:
  - commit
exclude: node_modules|.git|.tox|test_*.py
fail_fast: true
repos:

  - hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: mixed-line-ending
      - id: check-json
        files: \.(json)$
      - id: check-toml
        files: \.(toml)$
      - id: check-yaml
        files: \.(yaml)$
      - id: fix-encoding-pragma
        args: [ --remove ]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0

  - hooks:
      - id: isort
        entry: isort
        additional_dependencies: [ "toml" ]
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1


  - hooks:
      - exclude: (/settings/)
        id: black
        require_serial: true
        types:
          - python
    repo: https://github.com/ambv/black
    rev: 24.1.1

  - hooks:
      - id: flakeheaven
        exclude: (\.md$|\.ipynb$)
    repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.3.0

  - hooks:
      - entry: pylint
        files: \.py$
        id: PyLint
        exclude: ^test/
        language: system
        name: PyLint
    repo: local

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0
    hooks:
      - id: hadolint
        args: [ --ignore, DL3059, --ignore, DL3008 ]

  - repo: https://github.com/Trim21/poetry-check-lock.git
    rev: v0.0.5
    hooks:
      - id: poetry-check-lock
