version: '3.4'

services:
  mlinspect:
    image: mlinspect
    container_name: mlinspect
    restart: unless-stopped
    build:
      context: .
      target: final
    ports:
      - "8888:8888"
    volumes:
      - .:/project
    command: jupyter notebook --no-browser --allow-root --ip="0.0.0.0"
