[tool.poetry]
name = "mlinspect"
version = "0.0.1.dev0"
description = "Inspect ML Pipelines in the form of a DAG"
authors = ["Stefan Grafberger <stefangrafberger@gmail.com>"]
readme = "README.md"
license = "Apache License 2.0"
classifiers=[
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.9'
    ]

[tool.poetry.dependencies]
python = "3.9.16"
scikit-learn = "1.3.0"
protobuf = "4.24.3"
pandas = "2.1.1"
numpy = "1.24.3"
six = "1.16.0"
nbformat = "5.9.2"
nbconvert = "7.8.0"
ipython = "8.15.0"
astpretty = "3.0.0"
astmonkey = "0.3.6"
networkx = "3.1"
more-itertools = "10.1.0"
pygraphviz = "1.11"
testfixtures = "7.2.0"
matplotlib = "3.8.0"
gorilla = "0.4.0"
astunparse = "1.6.3"
setuptools = "68.2.2"
scipy = "1.11.2"
statsmodels = "0.14.0"

[tool.poetry.group.dev.dependencies]
pylint = "2.17.5"
pytest = "7.4.2"
pytest-pylint = "0.19.0"
pytest-runner = "6.0.0"
pytest-cov = "4.1.0"
pytest-pycharm = "0.7.0"
pytest-mock = "3.11.1"
gensim = "4.3.2"
tensorflow = "2.13.0"
keras = "2.13.1"
jupyter = "1.0.0"
importnb = "2023.1.7"
seaborn = "0.12.2"
shap="0.42.1"
scikeras="0.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
addopts = "--pylint --pylint-rcfile=./pylintrc --cov=mlinspect --cov-report=xml"
testpaths = ["test"]