name: Combine PRs

on:
  workflow_dispatch:
    inputs:
      ci_required:
        description: 'If ci is required to combine prs.'
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v4.1.0
        with:
          ci_required: ${{ inputs.ci_required }}